version: 0.2

phases:
  install:
    commands:
      # Install Node.js and npm/yarn if not already part of the CodeBuild environment image
      # For example, if using a standard CodeBuild image with Node.js pre-installed:
      # - echo "Node version: $(node -v)"
      # - echo "npm version: $(npm -v)"
      - npm install # or yarn install if using yarn
  build:
    commands:
      - npm run build 
  post_build:
    commands:
  
